Clean up menu design
phildenhoff/logseq-hypothesis pull request #1
Opened 2022-05-04 15:53 UTC by phildenhoff

2022-05-04 15:53 UTC, phildenhoff commented
Current dependencies on/for this PR:
* main
  * **PR #1** <a href="https://app.graphite.dev/github/pr/phildenhoff/logseq-hypothesis/1" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  (this PR)

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/phildenhoff/logseq-hypothesis/1?utm_source=stack-comment).

2022-05-11 13:06 UTC, c6p requested changes
Thanks for theming. 😆  It was long overdue.

2022-05-11 13:06 UTC, c6p commented on src/App.vue
> -      await logseq.Editor.updateBlock(pagePropBlock.uuid, pagePropBlockString);
Let's also keep this one for now. It is there to upgrade pre-block or page properties from the old naming scheme. I should add a comment, sorry 😔. In the future, we may opt for modification.

2022-05-11 13:36 UTC, c6p reviewed
Thanks for the required uplifting of the UI.

I think, it is better to let the user see the full title. So, please remove all width constraints, let it fill the entire width when required. Since the long titles will push all the buttons to the left, I think, it is better to right-align them.

It seems Logseq provides a new settings UI, I want to move "Account Setup" there, though for now your UI looks pretty good.

Cheers

2022-05-11 18:18 UTC, phildenhoff commented
Thanks for taking the time to look this over @c6p — your notes on integrating into the Logseq settings UI & holding those annotation formatting changes for now are heard. I've actually just started using Logseq's settings page for my [Raindrop plugin](https://github.com/phildenhoff/logseq-raindrop) and it works great, so I'd definitely like to get it in here too.

Here's what I think I'd like to do:

- Split out my annotation formatting changes into a separate branch. I still want to use those, but I can appreciate that you don't want to randomly change everyone else's method for formatting annotations. Fair point!
- Change this PR to use Logseq's `getTheme()` function & `onThemeModeChanged()` callback to set the theme (instead of the hack I have now)
- Bring back page-level properties. I think I had an issue with these not appearing when using the `properties` field in `insertBlock`, but I'll take another look
- Right-align titles & remove width constraints

Then, in another PR

- Rip out "Account Setup" & use Logseq's built-in settings page, making sure that existing users can "just upgrade" without having to do any more setup. I'll likely base this on what I have in my [Raindrop plugin](https://github.com/phildenhoff/logseq-raindrop/blob/0d96de684f705d54594e9dcbae82cd9ffb90fcda/src/App.svelte#L1-L55):
  - First time users, when they open the extension, should see a link to the Settings page
  - All other users just see the "Fetch" button & the "Create page from Hypothesis notes" section

2022-05-11 19:37 UTC, c6p commented
Wow! It would be perfect @phildenhoff.

> I've actually just started using Logseq's settings page for my [Raindrop plugin](https://github.com/phildenhoff/logseq-raindrop) and it works great, so I'd definitely like to get it in here too.

It is great to hear, I've yet to play with the built-in settings. I'm also a raindrop user myself. It seems to have gained annotation support lately, too. I'll check out your plugin later.


> Then, in another PR...

Better than what I've in mind. 


> Bring back page-level properties. I think I had an issue with these not appearing when using the properties field in insertBlock, but I'll take another look

I think when the first block has some content, properties become block-level. So just removing line 339 should work.


> Split out my annotation formatting changes into a separate branch. 

I remember another user asking for templates in discord. I'll just let users set their own formats for all annotation types, and yours may be one of the prepopulated. 


> Right-align titles & remove width constraints

What I mean, right-align the buttons. But I'm fine either way. Anything you deem looking good and functional is ok with me.


Cheers

2022-05-12 09:38 UTC, phildenhoff commented on src/App.vue
> -      await logseq.Editor.updateBlock(pagePropBlock.uuid, pagePropBlockString);
I ended up resolving this by using `upsertBlockProperty` — `updateBlock` would actually just delete the blocks properties entirely, for whatever reason. I guess because the content was empty? Anyway, `upsertBlockProperty` seems to work great

2022-05-13 10:16 UTC, c6p commented on src/App.vue
> -      await logseq.Editor.updateBlock(pagePropBlock.uuid, pagePropBlockString);
I inadvertently said that it updates from a previous naming-scheme. Actually, it updates from a previous first-block format where there was content but not any properties. So an `updateBlock` is still necessary to clean this residual content. Though, you are right, `updateBlock` deletes all properties even with content. It seems either `content` overwrites the properties or `properties` in `updateBlock` just does nothing at all.

That might be a bug in logseq API. I will report there.

It is the only thing holding off this pull request. I'm going to merge it, as soon as I've found a workaround.

2022-06-08 23:25 UTC, phildenhoff commented
Closed by c6p/logseq-hypothesis#14

2022-06-08 23:25 UTC, closed without merging